feat:add request reload feature and subscribe feature
day1co/fastcache pull request #1
Opened 2022-01-28 02:11 UTC by kooks7

(fastcampus/fastbus를 이동한 PR입니다.)
## 개요
Fastbus를 Cloud pub/sub으로 변경하면서 기존에 cache reload를 위한 redis publish 기능을 Fastcache로 이동하기 위함

Fastbus에서 cache reload를 위해 broadcast publish를 사용하는 방법은 아래와 같습니다.

<img width="574" alt="Screen Shot 2022-01-28 at 11 05 17" src="https://user-images.githubusercontent.com/47456161/151474504-cd150a7e-a1e0-464e-87bf-64e87fddcf3d.png">

1. FASTCAMPUS 서버 중 하나의 인스턴스에서 redis에게 SYSTEM_RELOAD 채널로 reload 메시지를 publish 합니다.
reload 메시지를 publis 하는 케이스는 아래와 같습니다.
a. banner나 menu가 create, update 되는 경우
b. FASTCAMPUS 서버의 reload URL로 get 요청을 했을 경우
```javascript
const createBanner = async ({ data }) => {
  const result = await bannerDao.insert(data);
  // broadcast publish
  bus.publish(BusTopic.SYSTEM_RELOAD, 'BANNER', true);
  return result;
};
```

2. redis는 subscribe하고 있는 subscriber들에게 메시지를 publish 합니다.

3. FASTCAMPUS는 SYSTEM_RELOAD라는 채널을 subscribe 하고 있으므로 redis가 보낸 메시지를 받게되고 local cache를 update 합니다.
(패스트캠퍼스에서는 subscribe의 listener에 redis cahce를 invalidate하는 로직을 넣어서 redis cache에 저장된 payment method list를 제거하기도 합니다.)

[FASTCAMPUS에 subscribe 하고 있는 부분](https://github.com/fastcampus/fastcampus/blob/0c71806c6a3f5f5e39cd3d3589d12b128765c151/fastcampus/index.js#L45-L46)

## 설명
필요한 기능

1. redis publish
2. redis subscribe
[fastbus에서는 psubscribe](https://github.com/fastcampus/fastbus/blob/05baa326f50f7fc2b494425cb6ae5688e1f5ae46/src/fast-bus.ts#L74-L105)([psubscribe란](https://redis.io/commands/psubscribe) 패턴이 동일한 모든 channel을 구독하는 subscribe 함수)를 사용해서 broadcast publish와 message queue 두 기능 모두를 지원했습니다.

## 변경되는 부분
기존의 Fastbus에서는 redis pub/sub을 이용하여 개별 메시지를 queue에 넣고
reloadChannel의 prefix default 값은 bus:0: 입니다.

* broadcast
* onReload
* subscribe
* unsubscribe
메소드를 추가했습니다.

## 사용
* 구독자 추가: `bus.subscribe('SYSTEM_RELOAD')` (기존의 fastbus와 다르게 subscribe 등록을 해당 클래스 생성시에 하지 않기 때문에,사용하는 server를 기동할때 subscribe 등록을 해주어야 합니다.)
* 리로드 브로드캐스트: `bus.broadcast('BANNER')`
* 리스너 추가: `bus.onReload('BANNER', (target) => console.log('target'))`

2022-02-03 06:02 UTC, soomtong reviewed
fastcache 에 이 기능을 넣지 않고 FastBus 를 따로 생성해 사용하는 건 어떨까요?

2022-02-04 01:30 UTC, rageatm requested changes

2022-02-04 01:30 UTC, rageatm commented on src/FastCache.ts
> +  }
이건 cache입니다.
cache에 왜 broadcast, subscribe, unsubscribe 같은 기능이 있는 거죠?
어느 cache에 이런 기능이 있나요?

2022-02-04 01:31 UTC, rageatm commented on package.json
> +  "version": "0.0.11",
1.0.0은 시기상조라고 생각합니다

2022-02-04 02:28 UTC, kooks7 commented on src/FastCache.ts
> +  }
맞습니다! 영택님 코멘트 보고 다시 생각해보니, cache를 구현한 클래스에 해당 기능들이 들어가는 것이 조금 이상했습니다. 만약 redis cache에서 memcached로 변경하게 되면 해당 기능을 전혀 사용할 수 없는 상황이였습니다.

[fastbus에 broadcast 기능을 구현하는것 대신](https://github.com/day1co/fastbus/blob/d254823ac803536f7ea717bad79478ae15c450c8/src/cloud-pubsub-bus.ts#L21-L25),fastcache 레포안에 (영택님이 제안해주신 FastBus명은 fastbus의 FastBus 클래스 명과 겹치므로) FastReloader 같은 클래스를 추가하는것은 어떨까 합니다 👀

2022-02-04 02:55 UTC, rageatm commented on src/FastCache.ts
> +  }
...... 지난 회의 때 실장님이랑 얘기한 걸 제대로 이해 못한 거 같은데요.

지금 cache에 구현하려는게 뭔가요?
FastReloader 클래스가 왜 필요하고 그 안에 무슨 메소드가 있을 건가요?
일반적으로 cache api에 뭐가 있나요?

2022-02-04 10:33 UTC, kooks7 commented
팀장님과 논의 한 결과, 해당 기능은 cache에 들어가는 것이 적절하지 않다고 판단해서 close 하도록 하겠습니다.
실장님가 추가 논의 후 fastcampus의 local cache 기능을 변경하고자 해서, 차주 승건님과 논의하도록 하겠습니다.
cc @rageatm @soomtong @plainOldCode

2022-02-04 10:33 UTC, closed without merging